//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaiSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] def_th06_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th06_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th07_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th07_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th08_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th08_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th09_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th09_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th095_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th095_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th10_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th10_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th11_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th11_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th12_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th12_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th125_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th125_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th128_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th128_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th13_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th13_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th14_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th14_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th143_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th143_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th15_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th15_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] def_th16_cfg {
            get {
                object obj = ResourceManager.GetObject("def_th16_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
